---

- hosts: prometheus
  become: yes
  vars_files:
    - vars/main.yml

  roles:
    - prometheus

#- hosts: node_exporter
#  vars_files:
#    - vars/main.yml
#  roles:
#    - node-exporter

#- hosts: alertmanager
#  vars_files:
#    - vars/main.yml
#  roles:
#    - alertmanager
