---

#- hosts: all
#  become: yes
#  vars_files:
#    - vars/main.yml


#  roles:
#    - { role: cadvisor, when: pkg == "cadr" }
#    - { role: node-exporter, when: pkg == "node" }
#    - { role: alertmanager, when: pkg == "alert" }
#    - { role: prometheus, when: pkg == "prome" }
#- hosts: cadvisor
#  roles:
#    - cadvisor

#- hosts: node_exporter
#  vars_files:
#    - vars/main.yml
#  roles:
#    - node-exporter

#- hosts: alertmanager
#  vars_files:
#    - vars/main.yml
#  roles:
#    - alertmanager

- hosts: prometheus
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - prometheus
