---

#Cadvisor installation
- hosts: cadvisor
  vars_files:
    - vars/main.yml
  roles:
    - cadvisor

#node_exporter installation
- hosts: node_exporter
  vars_files:
    - vars/main.yml
  roles:
    - node-exporter

#alertmanager installation
- hosts: alertmanager
  vars_files:
    - vars/main.yml
  roles:
    - alertmanager

#prometheus installation
- hosts: prometheus
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - prometheus
