---

- hosts: cadvisor
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - cadvisor

#- hosts: node_exporter
#  vars_files:
#    - vars/main.yml
#  roles:
#    - node-exporter

#- hosts: alertmanager
#  vars_files:
#    - vars/main.yml
#  roles:
#    - alertmanager


#- hosts: prometheus
#  become: yes
#  vars_files:
#    - vars/main.yml
#  roles:
#    - prometheus
