---
# tasks file for alertmanager


- name: "Alertmanager | Add group prometheus"
  group:
    name: "{{ prometheus_group }}"
    system: yes
    state: present

- name: "Alertmanager | Add Prometheus system user"
  user:
    name: "{{ prometheus_owner }}"
    comment: prometheus to run exporters
    shell: /sbin/nologin
    system: yes
    state: present
    group: "{{ prometheus_group }}"

- name: "Alertmanager | Create installation folders"
  file:
    path: "{{ item }}"
    owner: "{{ prometheus_owner }}"
    group: "{{ prometheus_group}}"
    mode: 0775
    state: directory
  with_items:
    - /Monitor/alertmanager
    - /Monitor/tmp

- name: "Alertmanager | Download alertmanager"
  get_url:
    url: "{{ alertmanager_download_url }}"
    dest: "{{ monitor_tmp_dir }}"
    mode:  0775

- name: "Alertmanager | Unarchive alertmanager downloaed file"
  unarchive:
    src: "{{ monitor_tmp_dir }}/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
    dest: "{{ alertmanager_install_dir }}"
    owner: "{{ prometheus_owner }}"
    group: "{{ prometheus_group }}"
    mode: 0775
    remote_src: false


- name: "Alertmanager | Create alertmanager Service template"
  template:
    src: alertmanager.service.j2
    dest: "/etc/systemd/system/alertmanager.service"
    owner: "{{ prometheus_owner }}"
    group: "{{ prometheus_group }}"
    mode:  0755
  when: ansible_distribution_major_version > '6'

- name: "Alertmanager | Placing alertmanager config file"
  template:
    src: alertmanager.yml.j2
    dest: "{{ alertmanager_install_dir }}/alertmanager-{{ alertmanager_version }}.linux-amd64/alertmanager.yml"
    owner: "{{ prometheus_owner }}"
    group: "{{ prometheus_group }}"
    mode:  0755

- name: "Alertmanager | start alertmanager service"
  systemd:
    name: alertmanager
    state: restarted
    daemon_reload: yes
